import image1 from '../assets/rps.jpeg'
import image2 from '../assets/steak.jpeg'
import image3 from '../assets/portfolio.jpeg'



export const ProjectList = [
  {
    title: 'e-Commerce Cheesesteak Website',
    image: image2,
    skills: 'React, CSS',
    description:
      'A mock e-commerce app that allows users a choice of different philly cheesesteaks. Users can add steaks to the cart, update the cart and complete an order form. This project showcases the use of context API for state management, the implementation of the react router and some basic form validation.',
    url: 'https://github.com/janeishahutley/cheesesteak-react-app',
    path: 'https://janeishahutley.github.io/cheesesteak-react-app/',
  },

  {
    title: 'Rock Paper Scissors Game',
    image: image1,
    skills: 'React, CSS',
    description:
      'A game of rock, paper, scissors that allow users to select an image of rock, paper or scissors. The computer selection is autogenerated. The first to reach 10 wins the game.',
    url: 'https://github.com/janeishahutley/rcok-paper-scissors',
    path: 'https://janeishahutley.github.io/rcok-paper-scissors/',
  },

  {
    title: 'Portfolio Project',
    image: image3,
    skills: 'HTML, CSS, JavaScript',
    description:
      'A portfolio that presents various projects and provides information about me as it pertains to my pursuit of becoming a software engineer.',
    url: 'https://github.com/janeishahutley/janeisha_h_portfolio',
    path: '',
  },
]
